from tkinter import *
#import tkinter as tk
from PIL import *
delete_window = Tk()
delete_window.geometry('1600x768')
delete_window.configure(bg='honeydew3')
def show():
    frame_body=Frame(delete_window,width=600,height=400,background='honeydew3',highlightbackground='black',highlightthicknes=5)
    frame_body.grid(row=1,column=0,padx=20,pady=20,ipadx=5,ipady=5,columnspan=2)
    frame_body.place(x=530,y=205)
    name = Label(delete_window, text="NAME:",font=('Times New Roman',18,'bold'),bg='honeydew3')
    name.place(x=550,y=260)
    department= Label(delete_window, text="DEPARTMENT:",font=('Times New Roman',18,'bold'),bg='honeydew3')
    department.place(x=550,y=310)
    cgpa = Label(delete_window, text="CGPA:",font=('Times New Roman',18,'bold'),bg='honeydew3')
    cgpa.place(x=550,y=360)
    ssc = Label(delete_window, text="SSC AGGREGATE:",font=('Times New Roman',18,'bold'),bg='honeydew3')
    ssc.place(x=550,y=410)
    hsc = Label(delete_window, text="HSC AGGREGATE:",font=('Times New Roman',18,'bold'),bg='honeydew3')
    hsc.place(x=550,y=460)
    status = Label(delete_window, text="STATUS:",font=('Times New Roman',18,'bold'),bg='honeydew3')
    status.place(x=550,y=510)
uidEntry = Label(delete_window, text="UID:",font=('Times New Roman',21,'bold'),bg='honeydew3')
uidEntry.place(x=30,y=100)
text_box = Text(delete_window, height=2, width=40)
text_box.place(x=102, y=104)
delete_button = Button(delete_window, text="Delete", font=('Times New Roman',18),width=8)
delete_button.place(x=100,y=150)
show_button=Button(delete_window, text="Show", font=('Times New Roman',18),width=8,command=show)
show_button.place(x=240,y=150)
delete_window.mainloop()