s = set()
print(type(s))
s.add(1)
s.add(2)
print(s)
s1 = s.union({12,22,1,2})
print(s,s1)
s_for_list = set([1,2,3,4])
print(s_for_list)
print(type(s_for_list))
l = [1,2,3,4]
s_for_list1 = set(l)
print(s_for_list1)
print(type(s_for_list1))